feat:
  - changed-files:
      - any-glob-to-any-file:
          - cmd/**
          - internal/**

chore:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - go.mod
          - go.sum
          - docker-compose.yml

test:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*_test.go"
          - tests/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - AGENTS.md
          - README.md
